title: Eric Liu
description: Machine Learning / RL / Systems
url: "https://eliu4913.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "default"
include: ["_pages", "assets/css"]

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed

author:
  name: Eric Liu
  avatar: /assets/images/me.jpg
  bio: "M.S. in Computer Science at USC"
  location: "Los Angeles, CA, USA"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:eliu4913@usc.edu"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/eliu4913/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/eliu4913"

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "main"
